### ISSUE TITLE
"include-in-header" File <filename> not found in resource path

### ISSUE THREAD

**Issue by plbt5** [htdebeer/pandocomatic#101]
I have created a setup to organise different project files in distinct subdirectories. One of those relates to the file that I want to include in the header:
```
./
+templates/myHdr.sty
```
I've modified the `pandocomatic.yaml` accordingly:
```
...
   pandoc:
      include-in-header: './templates/myHdr.sty' # To easily include packages.
...
```

This works fine until the source markdown file is moved into its own subdir, e.g.,
```
./
+templates/myHdr.sty
+src/docs/mydoc.md
```

This results in the error `File myHdr.sty not found in resource path`

Apparently, the resource path is established relative to the source markdown location. This is confirmed by a flawless operation again when changing the setup in `pandocomatic.yaml` into:
```
...
   pandoc:
      include-in-header: './../../templates/myHdr.sty' # To easily include packages.
...
```

This is somewhat counterintuitive, where one, or at least I, would expect the paths to be established from the working directory, i.e., the root of the project that houses `pandocomatic.yaml`. Is the current operation based on an explicit design decision, or is it a by-effect of the current code?

**Comment by htdebeer** [comment]
I think the latter, but I have to look into this. Which in itself suggests that the behavior is not as consistent as expected or hoped for. 

Unless we decide to change behavior, any change will result in breaking behavior. And If I'm changing this behavior, I might as well rewrite the whole path resolution behavior from scratch, but now well-reasoned and consistently. For example, it might make sense to separate the "single file conversion" behavior from the "convert directory / static site generation" behavior.

**Comment by plbt5** [comment]
Thanks for looking into this.

If anything, there currently exists a work-around or "correct way" to go about this, i.e., by explicitly including the path to the subject file in the `pandocomatic.yaml` specification. So the community can proceed with it, turning this issue into a not-so-high-priority one.

I'm available for discussions but only if you consider such useful.

**Comment by plbt5** [comment]
**Additional Error message**

Working on a similar but different project, with identical  file/directory setup but with the non-corrected `pandocomatic.yaml`, i.e., 
```
...
   pandoc:
      include-in-header: './templates/myHdr.sty' # To easily include packages.
...
```
I was confronted with another error message, as follows:

```
/Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:332:in `throw': uncaught throw #<Paru::Error: Unable to run pandoc via command 'pandoc	--verbose \\ (UncaughtThrowError)
	--from=markdown \\
	--to=latex \\
	--standalone \\
	--filter=/Users/paulbrandt/.local/share/pandoc/filters/assimilateMetadata.rb \\
	--template=/Users/paulbrandt/.local/share/pandoc/elsarticle.latex \\
	--include-in-header=templates/addstyles.sty \\
	--natbib \\
	--bibliography=src/bib/CitedByMe-2021-swSemantics.bib \\
	--citation-abbreviations=/Users/paulbrandt/.local/share/pandoc/cite-abbr.json \\
	--reference-links': Broken pipe>
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:332:in `rescue in run_converter'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:307:in `run_converter'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:157:in `convert'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:222:in `block in pandoc'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:184:in `chdir'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:184:in `pandoc'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:135:in `convert_file'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:86:in `run'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/command.rb:129:in `execute'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_multiple_command.rb:99:in `block in execute'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `each'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `execute'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/pandocomatic.rb:105:in `run'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/bin/pandocomatic:3:in `<top (required)>'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/bin/pandocomatic:25:in `load'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/bin/pandocomatic:25:in `<main>'
/Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:314:in `write': Broken pipe (Errno::EPIPE)
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:314:in `<<'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:314:in `block in run_converter'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open3.rb:227:in `popen_run'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/3.0.0/open3.rb:102:in `popen3'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:313:in `run_converter'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/paru-0.4.3/lib/paru/pandoc.rb:157:in `convert'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:222:in `block in pandoc'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:184:in `chdir'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:184:in `pandoc'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:135:in `convert_file'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_command.rb:86:in `run'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/command.rb:129:in `execute'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_multiple_command.rb:99:in `block in execute'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `each'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/command/convert_file_multiple_command.rb:98:in `execute'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/lib/pandocomatic/pandocomatic.rb:105:in `run'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/pandocomatic-0.2.8/bin/pandocomatic:3:in `<top (required)>'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/bin/pandocomatic:25:in `load'
	from /Users/paulbrandt/.rbenv/versions/3.0.3/bin/pandocomatic:25:in `<main>'

```

I'm not sure why the error message differed. I diff'ed the `pandocomatic-yaml` files of each project: no differences found. I used the very same latex template. I even replaced the yaml-block of the new project with the one from the old project to see how that would influence the error message. All to no avail.

**Comment by htdebeer** [comment]
Looking at your error message, I also wonder: why isn't there an input and output file in the verbose pandoc command at the top. Something is going very wrong here in pandocomatic!

**Comment by htdebeer** [comment]
Looking in pandocomatic's code, I see that both `bibliography` and `include-in-header` are marked as "option with path". However, pandocomatic has different behavior for options that can occur more than once, like `include-in-header`, and options that can occur only once, like `bibliography`. The former, uses the "absolute destination path" when selecting the path to use, and the latter uses the specified destination path. 

I don't know why this difference exists, so I suspect one of them is an error. I can try to align the behaviors and then prefer the behavior of `bibliography`, but this will affect all options that can occur more than once and have a path parameter.

**Comment by htdebeer** [comment]
I've started looking into this issue. If I understand the problem correctly, there's some confusion what a local path means in a template. There seem three different interpretations:

1. the current working directory, or
2. the input source file we're currently processing, which might be located in a subdirectory of or even completely elsewhere from the current working directory, or
3. the file the template is defined in

Observations:

- For an internal template, option 2 is the only one that makes sense.
- If a template is defined in a configuration file that's located in the current working directory, 1 and 3 are the same.
- If a template is defined elsewhere, all three can make sense depending on our interpretation.

According to the [manual](https://heerdebeer.org/Software/markdown/pandocomatic/#pandocomatic-templates), the following should hold:

> All local paths start with ./. These paths are local to the document being converted. When converting a directory tree, the current directory is being prepended to the path minus the ./.

Which seem to suggest that local paths follow interpretation 2. 

I am not sure this is the most natural choice, particularly for templates used all over the place. Changing this behavior seems dangerous, though, as it would not be backwards compatible. And for global used templates, we already have the data directory we can set. Still, more control about where a path points to might be convenient.

Like we did for the root directory, we could a tag to a path to mark it as "start from this file". Say, `$TEMPLATE$`, or so. And also one for the working directory, like `$WORKING_DIR$`.

What do you think about this?

**Comment by htdebeer** [comment]
I've been thinking about my suggested solution a bit more, and found some issues:

- Either suggestion for special path is potentially dangerous because the input directory and output directory can be totally separate. For example, when using the `--css` option in pandoc that's relative to the working directory or template directory, you could end up with a path pointing to a directory outside of the regular scope of the output file's path.

  This wouldn't be an issue for preprocessors and the like that use used during the conversion but don't show up in the output. However,  for URLs and paths that end up in the output, like includes, css, before/after, this is problematic.
  
  I don't want to introduce different path behavior for different situations, because that's confusing.
- Although a path relative to template makes sense from the point of a template author, that's less true for the path relative to the working directory. That variant would be more clear to the document writer, I suppose.

Furthermore, using the data directory relative paths or the new environment variable substitution feature (#103), I think template writers have enough power to specify paths. Similarly, document writers can always use local paths in their local or internal templates that are easy to understand and configure.

For now, I will not implement these two special directories `$TEMPLATE$` and `#WORKING_DIRECTORY$` because I am not convinced they are needed or will introduce more confusion than they resolve.
