### ISSUE TITLE
Manual: add order of inheritance of configuration files 

### ISSUE THREAD

**Issue by plbt5** [htdebeer/pandocomatic#111]
The capability to inherent configuration data from multiple cascaded configuration files (allowing to overwrite or add or fallback to default options to the configuration of pandocomatic) has been [added end of last year](https://github.com/htdebeer/pandocomatic/issues/96).

I wasn't sure anymore about the order of cascading, that is, what is the order in which what configuration files are processed / overwritten. I consulted the manual but I couldn't get an answer to that particular question.

Please add that information as a linear cascading, and additionally, please document how the order that pandocomatic shows the config files used (when it runs in verbose mode) should be interpreted; I assume that bottom configuration extends/overwrites the ones above.

Thanks a lot,
Paul

**Comment by htdebeer** [comment]
I have updated the documentation and added a [short section on pandocomatic's configuration hierarchy](https://heerdebeer.org/Software/markdown/pandocomatic/#pandocomatics-configuration-hierarchy).

**Comment by plbt5** [comment]
That's precisely what I was missing; thanks! 

One last feature request: Add a line that indicates that the Extension rules will be followed, where (1) will be extended by (2.1) that will be extended by (2.2) that will be extended by (3), when the configuration files are available.

**Comment by htdebeer** [comment]
Thanks for the addendum. Makes the section more clear. I've updated the documentation.
