### ISSUE TITLE
Finding pandocomatic.yaml file

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#14]
I've had this problem since I started playing with pandocomatic. If I omit `-c` on the commandline then the yaml file cannot be found. If I specify the absolute path: `-c /Users/ian/.pandoc/pandocomatic.yaml` then it works. From the documentation it should search the pandoc data dir right?

NOTE: /Users/ian/.pandoc/pandocomatic.yaml does exist BUT it is a symbolic link  — even if I make it a real file it still doesn't work, so I don't think this is symbolic link issue.

```
👉  pandocomatic -i min.md -o min.html
No such template: 'test'.
```

```
👉  pandoc -v
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4
Default user data directory: **/Users/ian/.pandoc**
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by htdebeer** [comment]
It should look in the pandoc data directory, yes. 

It seems the issue is with the underlying pandoc wrapper, which has trouble with pandoc's version number now it consists of four numbers.

I've updated that library in version 0.1.3.3.
