### ISSUE TITLE
[Feature Request] Postflight Option

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#18]
Currently the postprocessor is a STDIN / STDOUT system. It would be good to have a section after all postprocessors have finished where one could run a postflight tool, to clean up temporary files, run `latexmk` etc. In this case it would be good to be able to pass command-line options and the output filename.

```yaml
postprocessors: []
postflight:
    - cmd: "latexmk"
       args: "-xelatex -f $1"
    - cmd: "latexmk"
       args: "-c"
```

$1 would be the output file[s] in this case. Panzer also has a `cleanup` section, but just running two postflights would be the same. What do you think?

**Comment by htdebeer** [comment]
As a workaround, you can write a postprocessor that just copies STDIN to STDOUT while doing something with the environment.

In general, I think it would be great to have a way to assign options to filters and processors. That would allow for more general scripts, and thus less work for users of pandocomatic / pandoc.

If you're interested in a cleanup section, would you also like to have a startup section, i.e. "preflight" in your terms?

**Comment by iandol** [comment]
It does seem logical to have: `preflight[cmd]`, `preprocessor[stdin]`, `filter[json]`, `postprocessor[stdin]`, `postflight[cmd]`, & `cleanup[cmd]` — but I personally wouldn't use all of these!!!

I don't have a usecase for `preflight`, but perhaps other users would, as it is [cmd]+options?

It is nice to distinguish between [cmd] tools and [stdin] tools, so perhaps only [cmd] tools should accept options/args?

**Comment by htdebeer** [comment]
Currently, I use "options/args" in my filters via metadata. For example, in a filter to number sections, figures, and the like, the template to use to number things can be set. And for processors, I can imagine a processor that generates images where you'd setup the dimensions of the images on a case to case basis, or so.

But with filters we have to adhere to whatever the pandoc community starts using, I suppose.

As for the preflight: I like the symmetry :-) Furthermore, the concept is the same as for postflight, only on the other end of the process. Once postflight has been added, adding preflight shouldn't take much work. Plus, thinking up a more general scheme for these things might be advantageous in the long run.

**Comment by htdebeer** [comment]
Now that you've got me thinking about all this. Does it make sense to be able to define/use these preflight/postflight scripts for directories as well when using pandocomatic to convert whole directory trees?

I suppose this should be added somehow to the `pandocomatic.yaml` files in the directories.

Maybe we should create a wiki page to design pandocomatic 0.2.x?

**Comment by iandol** [comment]
I've just created a skeleton wiki page.

Regarding file vs. directory, I hadn't though about it as I've never used pandocomatic that way (I only convert single docs). I suppose a pre|postflight script would be more efficient if you passed a directory and let it manage, but then you lose the control about globbing etc. that pandocomatic does right? In which case it would be better to run pre|postflight per file. If you wanted to be fancy, you could add a scope option? 

```yaml
preflight:
    - cmd: "dostuff"
       args: "-v $1"
       scope: "file"
```

**Comment by htdebeer** [comment]
Nice work with the wiki page!

Currently the dir converter only updates the templates in the context and then, for each file, it calls the file converter, and for each directory it calls the dir converter. There is no interference from the dir converter when you only convert one file. Nevertheless, maybe it is a good idea to separate the two modes of running pandoc more clearly. Maybe with a subcommand or a command line option.

**Comment by htdebeer** [comment]
I've created "setup" and "cleanup" sections in templates. Like the preprocessors and postprocessors, there are just a list of scripts to run. I'll create a new issue to also allow command line options to scripts in setup, cleanup, preprocessors, and postprocessors.
