### ISSUE TITLE
[Feature Request] Verbose / Report output mode?

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#24]
Hi Huub,

This is low priority, but looking into the pandocomatic source, I think it shouldn't be too difficult to generate a verbose report about the pandocomatic conversion. For example it would be nice to see the final command line and combined metadata sent to pandoc. Paru can extract the metadata, and pandocomatic has the command line options.

**Comment by htdebeer** [comment]
Added! You can enable it with the `--debug` or `-b` flag.

**Comment by htdebeer** [comment]
Also, I've released version 0.1.4!

**Comment by iandol** [comment]
Cool thanks! It would be neat if we could see the metadata too: Panzer does this, generating both a text and a json log when using --debug.

**Comment by htdebeer** [comment]
Which metadata do you mean? The YAML metadata in a file that is being converted or the current pandocomatic context in which the file is being converted?

**Comment by iandol** [comment]
The YAML metadata that is present in the document, for example Panzer gives this as overly verbose tidied json output which is overkill. I'm not sure what the pandocomatic context is, does it include document metadata or only internal conversion settings?

**Comment by htdebeer** [comment]
The pandocomatic context is the current set of templates and pandocomatic settings that are active. When running pandocomatic on a directory, in each directory these templates and settings can be overridden. In a markdown file you can also override a template's options. This context can be used to discern why pandocomatic uses a certain pandoc invocation.

I could create a debug report per conversion like:
- pandocomatic context (in YAML format?)
- markdown YAML metadata (in YAML format?)
- pandoc invocation command string

**Comment by iandol** [comment]
Panzer's logs are quite confusing actually (two files get produced), here they are for a simple pandoc conversion: https://gist.github.com/iandol/94d50e00483c6dabfb8ec879cd392255

Because pandocomatic doesn't handle metadata separately from command-line options ( #16 ), I doubt there would be anything in the pandocomatic context different from the document metadata  that would silently override pandoc settings. I do see your point that for directory conversion a different set of options may occur for each file conversion, but shouldn't this be completely specified in the [command line log + the other document metadata]?

This is very minor, perhaps it is best to leave it as it is in 0.1.4, unless you also think having the metadata reported makes sense...

**Comment by htdebeer** [comment]
We can think about it more and come back to it when we need it.

For me, a debug option would help me hunt down *why* some conversion is the way it is when it isn't what I expected it to be. So, if I print the pandoc invocation and it isn't what I expected, how can I find out why that pandoc invocation was generated?
