### ISSUE TITLE
Filenames with spaces are not handled properly

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#25]
If I have a file "This Test.md", and I run it through pandoc directly, it is fine. But using pandocomatic, I get:

```
👉  ~/Code/pandocomatic/test/pandocomatic.rb "This Test.md"
pandoc: and: openFile: does not exist (No such file or directory)
Pandocomatic needed 0.6 seconds to convert 'This Test.md'.
```

I've tried both `"This Test.md"` and escaping `This\ Test.md`.

The standard library module `Shellwords` handles escaping so perhaps that can be used? But it isn't as simple as escaping in cli.rb as File.exists? can't handle escaped filenames. I tried to debug it and  convert_file_command.rb#91 the input is loaded and readable, but when invoking the pandoc method (using pry-byebug to step debug it does)it errors. So I actually think the problem is not the `input` but the `output` and paru/pandoc.rb complains at line 61...

```
[17] pry(#<Paru::Pandoc>)> @options
=> {"from"=>"markdown",
 "to"=>"docx",
 "standalone"=>true,
 "dpi"=>300,
 "toc"=>false,
 "output"=>"./This Test.docx"}
```

```
From: /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.2/lib/paru/pandoc.rb @ line 62 Paru::Pandoc#convert:

    59: def convert input
    60:   output = ""
    61:   IO.popen(to_command, "r+") do |p|
 => 62:     p << input
    63:     p.close_write
    64:     output << p.read
    65:   end
    66:   output
    67: end

[22] pry(#<Paru::Pandoc>)> pandoc: and: openFile: does not exist (No such file or directory)
```

**Comment by iandol** [comment]
I can fix the error if I add:

```ruby
destination = destination.shellescape
```

after line 89 of pandocomatic.rb — BUT I won't create a pull request as I think this may be a bit fragile. Maybe it is better to handle this in paru itself, as it is using popen to run pandoc?

**Comment by htdebeer** [comment]
Nice catch! I do not use spaces in file names myself, so I wouldn't have found it.

I'll look into this for both paru and pandocomatic over the weekend. I'll add some tests with file names with spaces as well so it'll be a bit more robust going forward.

**Comment by htdebeer** [comment]
I upgraded paru to version 0.2.4.3 with your shellescape suggestion. All string-type command line options to pandoc are now shellescaped. I generated new gem for pandocomatic: version 0.1.4.1
