### ISSUE TITLE
Allow command line options to scripts in the setup, preprocessor, postprocessor, and cleanup sections of templates

### ISSUE THREAD

**Issue by htdebeer** [htdebeer/pandocomatic#31]
Allow command line options to scripts in the setup, preprocessor, postprocessor, and cleanup sections of templates. Allow both:

    setup:
    - 'path/to/script.sh'
    - 'path/to/another/script.sh'

and

    setup:
    -  
        path: 'path/to/script.sh
        options:
        - "--argument"
        - "-o val"
    -
        path: 'path/to/another/script.sh
        options: ['-c']

or any mix of both.

**Comment by iandol** [comment]
Hi Huub, nice to see setup and cleanup script options!!! I was wondering how you intend to pass command-line options to pre/postprocessor scripts as they are STDIN/STDOUT stream filters and could be programmed in any language?

**Comment by htdebeer** [comment]
These processors are called as an external program with [Open3#capture2](http://ruby-doc.org/stdlib-2.1.0/libdoc/open3/rdoc/Open3.html#method-c-capture2). It does not matter much if I call it with `'myprogram'` or `'myprogram --some --options'`, I suppose. So, the script plus the command line options are converted to one command string and executed. This is not much different from how `Paru::Pandoc#convert` works.

**Comment by htdebeer** [comment]
Now that I am thinking about it, you could also use `myprogram --some --options` directly without the need of using an object like 

    name: 'myprogram'
    options: ['--some', '--options']

I suppose. It would make the templates more succinct and there is less confusion how these command line options are send to the program. What would have your preference?

**Comment by iandol** [comment]
I personally prefer the more verbose `name:` + `options:` syntax (more logical to my mind), but I do agree that it would be simpler just to specify everything on one line, so perhaps that makes more sense for general users?

**Comment by htdebeer** [comment]
Everything on one line should also be easier to implement, so I'll look into that.

Then again, when people start using paths with spaces, it might be harder to implement well. How can I determine the program to run from a string like `'/home/user/My Documents/bin/program --an --option'`? On the other hand, it should be properly escaped anyway, even in the more verbose way of specifying program and options.

**Comment by iandol** [comment]
I think it should be up to the user to correctly escape their path, and I then assume pandocomatic will just pass the command line entered by the user as-is to Ruby's popen...

**Comment by htdebeer** [comment]
Processors of any kind can have parameters. For example, specifying a preprocessor like:

```
preprocessors:
-  'add_parameters_to_metadata.rb these are arguments'
```

will run `add_parameters_to_metadata.rb` with arguments `these`, `are`, and `arguments`. You can access them in the script. See also `examples/data-dir/preprocessors` for two examples.
