### ISSUE TITLE
Return <> 0 on error

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#39]
If Pandocomatic gets an error from Pandoc, it still itself returns 0 back to the calling app:

```
:: Running: /Users/ian/.rbenv/shims/pandocomatic --debug Pinna.md 
::: (3) + converting Pinna.md 2 times:
::: (2)   - convert Pinna.md -> Pinna.docx
::: pandoc	--from=markdown \
::: 	--to=docx \
::: 	--standalone \
::: 	--filter=/Users/ian/.pandoc/filters/removeHR \
::: 	--filter=/Users/ian/.pandoc/filters/authorRemoveHash \
::: 	--reference-doc=/Users/ian/.pandoc/custom.docx \
::: 	--dpi=300 \
::: 	--csl=/Users/ian/.pandoc/csl/neuron.csl \
::: 	--output=./Pinna.docx
::: Error running pandoc => error while running:
::: 
::: pandoc	--from=markdown \
::: 	--to=docx \
::: 	--standalone \
::: 	--filter=/Users/ian/.pandoc/filters/removeHR \
::: 	--filter=/Users/ian/.pandoc/filters/authorRemoveHash \
::: 	--reference-doc=/Users/ian/.pandoc/custom.docx \
::: 	--dpi=300 \
::: 	--csl=/Users/ian/.pandoc/csl/neuron.csl \
::: 	--output=./Pinna.docx
::: 
::: Pandoc responded with:
::: 
::: pandoc: /Users/ian/.pandoc/custom.docx: openBinaryFile: does not exist (No such file or directory)
::: 
:: exit status: pid 73414 exit 0
```

Notice the `exit 0`, returned to my scrivomatic ruby wrapper script (that runs pandocomatic with popen2e)

**Comment by htdebeer** [comment]
You're correct. Now pandocomatic catches all (expected) errors and prints an error message. It does not exit in an error state. I'll add an error status exit > 0. Maybe I'll use different error codes for different types of error, I'll look into that.

**Comment by htdebeer** [comment]
If there is an error while configuring pandocomatic before the conversion, error status code 1266 is used. If a known error happens during the conversion, error status code 1267 is used. If an unexpected error occurs, pandocomatic still crashes, but I've added a warning message asking the user to submit an issue in that case.
