### ISSUE TITLE
Very minor: relative path resolution

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#40]
If I use this in my document metadata:

```yaml
bibliography: ./pinna.json
```

I get this from pandocomatic:

```
pandoc	--bibliography=././pinna.json \
```

Notice that `./` has been prepended even though it was already present. This has no negative impact, `./././././` would still be the current directory!

**Comment by htdebeer** [comment]
Thanks for noticing this bug. I see the same happening here. Will be fixed next week.

**Comment by htdebeer** [comment]
This fix will be in the next release; will not create a separate one just for this issue because pandocomatic still does what it is supposed to do.
