### ISSUE TITLE
Capturing pandoc-citeproc stderr output

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#41]
Pandoc-citeproc will send information to stderr when, for example, a reference could not be found. This gets lost when pandocomatic runs pandoc+pandoc-citeproc, and it would be good if pandocomatic could preserve this info, particularly when running verbosely:

```
👉  pandoc -F pandoc-citeproc --bibliography=./sf-travel.json --csl=$HOME/.pandoc/csl/nature.csl -t docx -o Lu.docx Lu.md
pandoc-citeproc: reference levitt1994a not found
pandoc-citeproc: reference levitt1994a not found
pandoc-citeproc: reference hegdé2007 not found
pandoc-citeproc: reference levitt1994a not found
pandoc-citeproc: reference levitt1994a not found
pandoc-citeproc: reference levitt1994a not found
pandoc-citeproc: reference hegdé2008 not found
pandoc-citeproc: reference hegdé2008 not found
pandoc-citeproc: reference hegdé2007 not found
pandoc-citeproc: reference hegdé2007 not found

👉  pandocomatic -b Lu.md
/Users/ian/bin/pandoc	--csl=/Users/ian/.pandoc/csl/nature.csl \
	--bibliography=././sf-travel.json \
	--standalone \
	--filter=/usr/local/bin/pandoc-citeproc \
	--from=markdown \
	--to=docx \
	--reference-doc=/Users/ian/.pandoc/templates/custom.docx \
	--output=./Lu.docx
Pandocomatic needed 2.9 seconds to convert 'Lu.md'.
```

Paru already runs [pandoc with popen3](https://github.com/htdebeer/paru/blob/master/lib/paru/pandoc.rb#L287) so this is captured. Pandoc returns exit code of `0` in this case, with the pandoc-citeproc warnings returned via `stderr`, so by returning stderr + stdout pandocomatic should be able to preserve this info.

**Comment by htdebeer** [comment]
I suppose this happens to every filter, preprocessor, post processor, setup and cleanup scripts. The question is, however, should pandocomatic fail on every error or output on STDERR or try to continue on and only report the error?

For pandoc-citeproc an error is not that problematic as the result of the filter is still a valid pandoc AST. But how can we detect if a preprocessor or postprocessor has garbled the document beyond usable? 

The easiest way is to only report the error, i.e. just retransmitting STDERR, but try to continue on.

**Comment by iandol** [comment]
I would simply pass on the error. Pandoc returns `0` so it does not identify the fact as an error. Because filters depend on stdout, then they must by necessity utilise stderr for other communication, so I would think of stderr in this case as less an error and more an info/warn...

Now I think if a filter returns <>0 then Pandoc presumably panics (error in a filter stops pandoc working anyway), so I think we don't need to worry about major errors as that should be dealt with by Pandoc...

**Comment by htdebeer** [comment]
That makes sense. I see what I can do.

By the way, I updated the [pandocomatic manual](https://heerdebeer.org/Software/markdown/pandocomatic/) in preparation for the release of version 0.2. Feed-back welcome.

**Comment by htdebeer** [comment]
Added [printing pandoc warnings to STDERR in paru](https://github.com/htdebeer/paru/commit/c198195dc31a369d2869a63e66bbaf40678428be). Please update paru to version 0.2.5.9 for this to take effect in pandocomatic as well.

**Comment by htdebeer** [comment]
Fixed with [checkin to enable all pandocomatic template properties in a internal template](https://github.com/htdebeer/pandocomatic/commit/0bbc2a6616abb10af4625069a11803ddd45436c7).

**Comment by iandol** [comment]
Awesome Huub, many thanks!!! Confirmed the citeproc errors are now visible from pandocomatic, thus this issue is fixed!

What does that last checkin, "checkin to enable all pandocomatic template properties in a internal template" actually do?

You've done a great job of the manual, the description of extending templates is really nice. I saw a few typos, went to make a pull request but saw you fixed them already!

**Comment by htdebeer** [comment]
You now can also override or customize the `setup`, `preprocessors`, `metadata`, `postprocessors`, and `cleanup` sections of a template. Before you could only override or customize the `pandoc` section of a template. 

This makes things more consistent with regards to templates.

**Comment by iandol** [comment]
Ah, great! And congratulations on V0.2 🎆 🍺 😸

**Comment by htdebeer** [comment]
And thank you for your contributions for v0.2 :-)
