### ISSUE TITLE
trying out pandocomatic 0.2 first time user, unable to execute hello world example

### ISSUE THREAD

**Issue by agusmba** [htdebeer/pandocomatic#43]
Hi @htdebeer !

First of all thanks for making this amazing tool. I've been baking my own shell scripts for automating my pandoc invokations, but I'd like to move to your tested framework instead.

So I installed rubygems on my windows 7 box:

```
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
$ gem -v
2.6.13
```

Then I installed pandocomatic with `gem install pandocomatic`:

```
$ pandocomatic -v
Pandocomatic version 0.2© [...]
```

I created the hello-world file from the [quick-start example](https://heerdebeer.org/Software/markdown/pandocomatic/#using-pandocomatic) in the documentation:

```markdown
---
title: My first pandocomatic-converted document
pandocomatic_:
    pandoc:
       to: html
...

Hello *World*!
```

However when I called pandocomatic, I got the following error:

```
$ pandocomatic Hello-world.md
pandoc: \
: openFile: invalid argument (Invalid argument)
Error running pandoc => error while running:

pandoc  --to=html \
        --from=markdown \
        --standalone

Pandoc responded with:

pandoc: \
: openFile: invalid argument (Invalid argument)
```

My pandoc version is:

```
$ pandoc -v
pandoc.exe 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4 [...]
```

And if I call pandoc manually with the reported options all seems to work:

```
$ pandoc  --to=html  --from=markdown --standalone Hello-world.md
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 [...]
```

Am I doing something wrong?

Thanks!

**Comment by agusmba** [comment]
Just in case I also tried it with the latest dev pandoc 2.0 but I still get the same error.

**Comment by htdebeer** [comment]
As far as I can tell, you're not doing anything wrong. However, I have never run pandocomatic on the windows OS, so that might be an issue, somehow. I see that pandocomatic fails on running `pandoc`. Does windows understand the `\` to escape a newline in a command-line invocation?

**Comment by agusmba** [comment]
Yes, I actually tested it by copy/pasting it in my git-bash window from the pandoc error

**Comment by htdebeer** [comment]
I see if I can find a Windows 7 virtual machine to try to reproduce the issue.

**Comment by agusmba** [comment]
Mmmm, It is true that if I try it from a regular cmd window, I get an error if I use the \ escape:

```
D:\DatosUsuarios\agustin\fuentes\pandoc-issue-3901>pandoc  --to=html \
pandoc: \: openBinaryFile: does not exist (No such file or directory)
```

Not quite the same error, and it shouldn't affect me if I use git-bash (wishful thinking here)

**Comment by agusmba** [comment]
Sorry again, actually my box is a Windows 10 (home edition), I could re-test this tomorrow in a windows 7 box (my bad)

**Comment by htdebeer** [comment]
I can reproduce the issue on WIndows 7 with a fresh install of Ruby, pandoc, and pandocomatic.

I'll look into this, but it looks like it is related to the Windows environment.

**Comment by agusmba** [comment]
Thanks!
Let me know if I can be of any help.

**Comment by htdebeer** [comment]
It appears the issue is with the Ruby pandoc wrapper (paru) on Windows. I'll create an [issue](https://github.com/htdebeer/paru/issues/30) for it and try to solve it.

**Comment by htdebeer** [comment]
I've created a fix of paru and updated pandocomatic. The new release 0.2.0.1 should now also work on windows!

**Comment by agusmba** [comment]
Thanks for fixing this so fast!
I can confirm the first example now works.
I'll play more with it tomorrow.
