### ISSUE TITLE
pandoc-citeproc filter not found on windows?

### ISSUE THREAD

**Issue by agusmba** [htdebeer/pandocomatic#44]
Back to trying out pandocomatic (version 0.2.0.1)

**[EDITED to simplify the error report and add a simple test case]**

I edited a template with 

``` 
[...]
        pandoc:
            standalone: true
            filter:
                - pandoc-citeproc
[...]
```

Here is a minimum example if you need it.
[pandocomatic-44.zip](https://github.com/htdebeer/pandocomatic/files/1317358/pandocomatic-44.zip)

Executed with

```bash
pandocomatic -b -c pandocomatic-44.yaml pandocomatic-44.md
```

But pandocomatic complains about not finding it. It is looking in the `data-dir` directory instead of in the PATH:

```text
d:\DatosXP\docs\pandoc-issues\pandocomatic-44>pandocomatic -b -c pandocomatic-44.yaml pandocomatic-44.md

pandoc  --standalone --filter=d:/Usuarios/username/AppData/Roaming/pandoc/pandoc-citeproc --to=docx --toc --output=./pandocomatic-44.docx
Error running filter d:/Usuarios/username/AppData/Roaming/pandoc/pandoc-citeproc:
Could not find executable d:/Usuarios/username/AppData/Roaming/pandoc/pandoc-citeproc
Error running pandoc => error while running:

pandoc  --standalone --filter=d:/Usuarios/username/AppData/Roaming/pandoc/pandoc-citeproc --to=docx --toc --output=./pandocomatic-44.docx

Pandoc responded with:

Error running filter d:/Usuarios/username/AppData/Roaming/pandoc/pandoc-citeproc:
Could not find executable d:/Usuarios/username/AppData/Roaming/pandoc/pandoc-citeproc
```

`pandoc-citeproc` install dir is in the path:

```
d:\DatosXP\docs\pandoc>echo %PATH%
C:\Windows\system32;C:\Windows
;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
 Files (x86)\QuickTime\QTSystem\;[................];D:\Usuarios\username\AppData\Local\Pandoc\;[.........];C:\Program Files\Microsoft VS Code\bin
```

Messing around with `irb` and executing manually `Configuration.which` seems to find the executable:

```
$ irb
irb(main):002:0> File::PATH_SEPARATOR
=> ";"
irb(main):005:0> cmd = 'pandoc-citeproc'
=> "pandoc-citeproc"
irb(main):007:0> exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
=> [".COM", ".EXE", ".BAT", ".CMD", ".VBS", ".VBE", ".JS", ".JSE", ".WSF", ".WSH", ".MSC", ".RB", ".RBW"]

irb(main):008:0> ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
irb(main):009:1* exts.each { |ext|
irb(main):010:2* exe = File.join(path, "#{cmd}#{ext}")
irb(main):011:2> puts exe
irb(main):012:2> return exe if File.executable?(exe) && !File.directory?(exe)
irb(main):013:2> }
irb(main):014:1> end

C:\Program Files\Git\mingw64\bin/pandoc-citeproc.COM
C:\Program Files\Git\mingw64\bin/pandoc-citeproc.EXE
C:\Program Files\Git\mingw64\bin/pandoc-citeproc.BAT
C:\Program Files\Git\mingw64\bin/pandoc-citeproc.CMD
[...]
D:\Usuarios\username\AppData\Local\atom\bin/pandoc-citeproc.RBW
D:\Usuarios\username\AppData\Local\Pandoc/pandoc-citeproc.COM
D:\Usuarios\username\AppData\Local\Pandoc/pandoc-citeproc.EXE  <----- here it is!
LocalJumpError: unexpected return
        from (irb):12:in `block (2 levels) in irb_binding'
        from (irb):9:in `each'
        from (irb):9:in `block in irb_binding'
        from (irb):8:in `each'
        from (irb):8
        from C:/Ruby24-x64/bin/irb:11:in `<main>'
irb(main):015:0>
```

Not sure if this helps.

**Comment by htdebeer** [comment]
Pandocomatic does not resolve executables in the PATH. It has [three strategies of specifying and resolving paths](https://heerdebeer.org/Software/markdown/pandocomatic/#specifying-paths): 1) local tot he document to convert, 2) global to the operating system, and 3) relative to the data directory.

This means you have to 
- use the global path to `pandoc-citeproc` in your template
- create (symbolic) link to `pandoc-citeproc` in the data directory

As an aside, isn't the filter `pandoc-citeproc` run implicitly when encountering references in a document?

**Comment by agusmba** [comment]
Ah, my mistake then. You are right, the documentation never implied that filters would be searched for in the path.

However, since pandoc supports "--filter pandoc-citeproc" and I had seen several pandocomatic configuration [examples](https://github.com/iandol/scrivomatic/blob/master/pandocomatic.yaml) using directly pandoc-citeproc in the templates I thought it should work.

I'm not fluent in ruby, but looking at some [pandocomatic](https://github.com/htdebeer/pandocomatic/blob/master/lib/pandocomatic/command/convert_file_command.rb#L182) [code](https://github.com/htdebeer/pandocomatic/blob/master/lib/pandocomatic/configuration.rb#L270), it seemed that the `--filter` option was being treated differently and checked for the executable in the path.

I checked in a linux box and it works using `pandoc-citeproc` in the template directly.

Regarding the need to explicitly use pandoc-citeproc, I was not aware of it! However I just tested it removing the citeproc filter and I do not get citations so it mustn't run implicitly (at least in all cases).

I'll test some of your workarounds, but it seems that would make the templates less "portable".

Maybe I should try my luck at creating a docker image with pandoc and pandocomatic so that I can run them in linux.

And please forgive me if this comment comes across a bit harsh or petulant, I am indeed very grateful for having pandocomatic!

**Comment by htdebeer** [comment]
Your comments are more than fine. A free software project can only improve by the feed-back and suggestion of its users.

An you're right, the PATH is checked first when it is not a local or a global path (i.e., starts with `./` or `/` respectively). I do not use that feature often myself because I put all my filters and scripts in the data directory. But I'll update the documentation that the path will be checked.

This seems also one of the issues with running pandocomatic/paru on Windows. To be honest, I did not try pandocomatic on Windows till yesterday evening; you're the first Windows user!

I am not familiar with modern Windowses, but I'll try to look into these issues in the coming week.

**Comment by htdebeer** [comment]
To clarify, this check in the `PATH` only happens for filters, not for preprocessors, postprocessors, or the setup/cleanup scripts.

**Comment by agusmba** [comment]
Yes that's what I thought also.

**Comment by htdebeer** [comment]
Apparently, pandoc's default data directory does not exist? Do users need to create it themselves?

Anyway. If it cannot find pandoc's data directory it should use "`.`" rather than throwing an error. Pandocomatic should only throw an error when a *specified* data directory cannot be found.

**Comment by htdebeer** [comment]
It should work now with version 0.2.0.2.

**Comment by agusmba** [comment]
Thanks!
