### ISSUE TITLE
is the default for "recursive" true?

### ISSUE THREAD

**Issue by agusmba** [htdebeer/pandocomatic#46]
According to [the docs](https://heerdebeer.org/Software/markdown/pandocomatic/#converting-a-directory-tree-of-documents) recursive defaults to "true".

However if I don't include the settings part in my yaml configuration for pandocomatic, sub-folders are not checked.

It could be either a bug or an error in the docs.

Best regards,
  Agustín.

**Comment by htdebeer** [comment]
This is an interesting one. If no config file is specified, the [default configuration](https://github.com/htdebeer/pandocomatic/blob/master/lib/pandocomatic/default_configuration.yaml) is used instead. However, if you do use your own configuration file, the only setting that is being set anyway is the `skip` setting.

I'll add the `recursive` and `follow-links` settings as well. This will be in the next version whenever it'll be released.
