### ISSUE TITLE
Pandocomatic 2.0.2 can't find pandocomatic.yaml in Windows 10

### ISSUE THREAD

**Issue by mankewd** [htdebeer/pandocomatic#47]
I'm trying to use pandocomatic on Windows 10 and it can't seem to find/load the pandocomatic.yaml config file regardless of how I run pandocomatic from the command line. Here are my example files.

pandocomatic.yaml (appended .txt extension to upload to github)
[pandocomatic.yaml..txt](https://github.com/htdebeer/pandocomatic/files/1327826/pandocomatic.yaml.txt)

markdown sample file (appended .txt extension to upload to github)
[docomatictest.md.txt](https://github.com/htdebeer/pandocomatic/files/1327827/docomatictest.md.txt)

Windows command session with pandocomatic invokations and results. 
[PandocomaticTestLogtxt.txt](https://github.com/htdebeer/pandocomatic/files/1327828/PandocomaticTestLogtxt.txt)

Assistance appreciated. 

Thanks!

**Comment by htdebeer** [comment]
I cannot load your `pandocomatic.yaml` file either. Looking at its contents, it seems the indentation is all over the place. As indentation is important in [YAML](http://yaml.org/), this is a problem. If you indent your file as follows, it should work:

```{.yaml}
settings:
    recursive: true
    follow-links: true
    skip: ['.*', 'pandocomatic.yaml']
templates:
    doccies:
        glob: ['*.md']
        pandoc:
            standalone: true
            toc: true
            from: markdown
            to: pdf
```
