### ISSUE TITLE
LaTeX Postprocessor Filter

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/pandocomatic#50]
I trying to modify some LaTeX code before Pandoc converted it to PDF but I don't figure out how to do it. I thought that writing a postprocessing script will work but is doesn't. 

Any ideas?

**Comment by htdebeer** [comment]
Postprocessing won't work, unless you run the latex engine or pandoc in the postprocessing script itself. Pandocomatic processes files as follows:

    setup ↦ read input → pre … pre → pandoc → post … post → write output ↦ cleanup

So the input document will be converted by pandoc before any post processing script is run.

Possible solutions I see are:
- run pandoc during a preprocessor to generate the LaTeX file
- run pandoc during a postprocessor to generate the PDF
- run pandocomatic twice, first to generate the LaTeX file and then to generate the PDF file.

**Comment by xbelanch** [comment]
thanks a lot @htdebeer Third option seems to fit my need I guess
