### ISSUE TITLE
Document the standalone directive

### ISSUE THREAD

**Issue by ngirard** [htdebeer/pandocomatic#61]
The `standalone` directive, although appearing once in an example code from the [manual](https://heerdebeer.org/Software/markdown/pandocomatic/) (in § 9.1 "Defining a template"), is never explicitly mentioned nor documented.

I suggest to document it.

**Comment by htdebeer** [comment]
Thanks for your comment. I'd like to improve the documentation, but I cannot find the word "standalone" in section 9.1. I do find it twice in the [documentation](https://heerdebeer.org/Software/markdown/pandocomatic/), both times in chapter 3. But there it appears to be the [pandoc standalone option](https://pandoc.org/MANUAL.html#general-writer-options). 

Could you copy the context surrounding the unclear use of the `standalone` direction in the documentation here? Say two lines before and after, so I'll be able to find it.

**Comment by ngirard** [comment]
My bad: the `standalone` directive appears in the first example code from [Part I, Chapter 3](https://heerdebeer.org/Software/markdown/pandocomatic/#why-pandocomatic) of the guide.

**Comment by htdebeer** [comment]
That's all right. So, this `--standalone` option is a pandoc option. I am not sure the pandocomatic manual is the place to explain pandoc options.

Why do you want the `standalone` option documented specifically? What is the difference with the options `csl`, `mathjax`, and `bibliography` options that are also used in the same example in that regard?

**Comment by ngirard** [comment]
It might seem obvious to you, that the `--standalone` Pandoc option has its equivalent `standalone` directive in Pandocomatic ; but it was not to me.

The same goes with the other options. As I specifically struggled to figure out the state of affairs regarding `standalone`, I filled a bug report about it, and I realize it might be misleading.

How about adding a paragraph that explains that every Pandoc `--option` has a matching `option` in Pandocomatic ? (if it's the case, which I don't know).

**Comment by htdebeer** [comment]
Sure. Thanks for the feedback, because this is quite an essential part of a pandocomatic template.

I'll rewrite the documentation to state more clearly that the `pandoc` section contains *only* pandoc options. That these options are translated to an equivalent pandoc invocation.

**Comment by ngirard** [comment]
Great, thanks !

**Comment by htdebeer** [comment]
I will update and improve the documentation after I have finished implementing issue #65. For that issue I'll add functionality to pandocomatic and have to update the documentation anyway. However, it might take a bit longer for me to handle this issue.

**Comment by ngirard** [comment]
Thanks again for your efforts and documentation improvements !
