### ISSUE TITLE
Clarify the status of the files in the documentation directory with respect to the manual

### ISSUE THREAD

**Issue by ngirard** [htdebeer/pandocomatic#62]
The `documentation` folder has contents which can't be found in the [Pandocomatic manual](https://heerdebeer.org/Software/markdown/pandocomatic/).
This leaves the newcomer unsure:

- about which one is the source of truth, between the manual and the documentation directory;
- whether reading the manual is enough to grasp Pandocomatic, or the files in `documentation` are also a required reading.

Thus, a clarification would be welcome.

**Comment by htdebeer** [comment]
The pandocomatic manual and the project's Github `README.md` file are generated from the files in the documentation folder and the contents should be the same. However, I do see there's a `manual.md` and a `manual2.md`, where the latter has superseded the former. I'll overwrite the former with the contents of the latter, after which I'll remove `manual2.md`. This should resolve this issue.
