### ISSUE TITLE
Pandocomatic broken with Pandoc V2.7

### ISSUE THREAD

**Issue by iandol** [htdebeer/pandocomatic#64]
Pandoc has just implemented the XDG Base directory specification in V2.7:

https://github.com/jgm/pandoc/issues/3582 

```
❯ pandoc -v
pandoc 2.7
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.1, skylighting 0.7.7
Default user data directory: /Users/ian/.local/share/pandoc or /Users/ian/.pandoc
Copyright (C) 2006-2019 John MacFarlane
```

Pandoc can work with either, but now `pandocomatic` cannot find its config file:

```
❯ pandocomatic -b Test.md
No such template: 'docx-refs'.
```

Even if I try to force the config directory in pandocomatic I still get errors as paths are now resolved differently:

```
❯ pandocomatic -c /Users/ian/.pandoc/pandocomatic.yaml -b Test.md
(2)   - convert Test.md -> Summerfield_Collaboration.docx
pandoc  --csl=/Users/ian/Desktop/Compile_mmd/csl/apa-ian-injournal.csl \
        --standalone \
        --filter=/usr/local/bin/pandoc-citeproc \
        --filter=/Users/ian/Desktop/Compile_mmd/filters/removeHR \
        --filter=/Users/ian/Desktop/Compile_mmd/filters/simplifyMetadata \
        --filter=/Users/ian/Desktop/Compile_mmd/filters/prependAll \
        --bibliography=/Users/ian/Desktop/Compile_mmd/Core.json \
        --citation-abbreviations=/Users/ian/Desktop/Compile_mmd/cite-abbr.json \
        --from=markdown \
        --to=docx \
        --reference-doc=/Users/ian/Desktop/Compile_mmd/templates/custom.docx \
        --output=/Users/ian/Desktop/Compile_mmd/Summerfield_Collaboration.docx
pandoc-citeproc: PandocIOError "/Users/ian/Desktop/Compile_mmd/csl/apa-ian-injournal.csl" /Users/ian/Desktop/Compile_mmd/csl/apa-ian-injournal.csl: openBinaryFile: does not exist (No such file or directory)
Error running filter /usr/local/bin/pandoc-citeproc:
Filter returned error status 1
Error running pandoc => error while running:
```

The relative paths that used to go to `~/.pandoc` for filters, CSL files etc are now resolved to the current directory.

**Comment by iandol** [comment]
You can see my pandocomatic.yaml for the conversion to docx here:

https://github.com/iandol/dotpandoc/blob/master/pandocomatic.yaml#L46

I use relative paths like `filters/simplifyMetadata` which used to be completed to be relative to the pandoc data dir but now become relative to the current folder...

**Comment by iandol** [comment]
As an interim fix I will move all my pandoc data files into the compile folder...

**Comment by iandol** [comment]
OK, I probably should be using `-d` not `-c` 😝 — I can get pandocomatic to work with `-d` option...

**Comment by iandol** [comment]
Probably https://github.com/htdebeer/paru/blob/master/lib/paru/pandoc.rb#L230 needs to be updated...

**Comment by htdebeer** [comment]
I'll look into this. At a first glance, two possible solutions come to the fore:

1. Select one of the default data directories, from pandoc version 2.7 on, prefer `~/.local/share/pandoc` over `~/.pandoc`, if `~/.local/share/pandoc` does exist, use that one, otherwise try to use `~/.pandoc`. For older versions, try the existence of these two directories in the reverse order.
2. Use both directories as a data directory, but give preference to `~/.local/share/pandoc` for pandoc version 2.7 when trying to locate files.

I prefer solution 2, because it seems to be similar to the interpretation for pandoc itself. The only downside I see is that the look-up of files in pandocomatic is slightly more difficult to understand for our users. What's your opinion in this matter?

**Comment by iandol** [comment]
Yes, I think solution 1 is closer to what Pandoc are doing so it would be wise to follow that...

**Comment by htdebeer** [comment]
I have updated paru's version to paru 0.3.2.0, which supports pandoc 2.7. You'll find it in pandocomatic 0.2.4.1.

**Comment by iandol** [comment]
Confirmed to work with 2.7, thanks Huub!
