### ISSUE TITLE
Issues after update to pandoc 2.8

### ISSUE THREAD

**Issue by htdebeer** [htdebeer/pandocomatic#78]
After the update to pandoc 2.8 and paru 0.4.0, some tests of pandocomatic are failing.

**Comment by iandol** [comment]
Hi I commented on https://github.com/htdebeer/paru/issues/51 that even with paru 0.4 installed I see this:
```
The pandoc option 'shift_heading_level_by' (with value '1') is not recognized by paru. This option is skipped.
```
using pandocomatic 0.2.5.5. 

```
> gem list
…
pandocomatic (0.2.5.5)
paru (0.4.0, 0.3.2.4)
…
```

**Comment by htdebeer** [comment]
Yes, pandocomatic now only works with paru versions 0.3.2.*. I will change that and look into any issues that might occur when using pandocomatic with paru 0.4 / pandoc 2.8
