### ISSUE TITLE
Installation on OSX Catalina

### ISSUE THREAD

**Issue by TheChasman** [htdebeer/pandocomatic#86]
I'm trying to install the Gem on my Mac running Catalina. I'm getting a permissions error on Library in my own user and as an admin.

I gather the Gem system is locked down by Apple, which rather defeats the object.

Has anyone got this working? Or is there an alternate installation method... I can't find a dmg. 

I was a C programmer a long time ago so I know my way around a makefile but I'm very rusty.

**Comment by iandol** [comment]
@TheChasman — you normally need to use sudo to install on macOS. Ruby will be removed from macOS as a default tool from the next OS version, and so I would recommend installing your own version of Ruby anyway. IMO the best tool to do that is rbenv, I have some instructions for options when using pandocomatic here: https://github.com/iandol/scrivomatic/blob/master/Installing-Ruby.md

**Comment by htdebeer** [comment]
No update in over a month: closing this issue for now. Feel free to reopen with new information.
